name: CI workflows
on:
  push:
    branches:
      - main
<<<<<<< HEAD
      - feature/host-selection-api-conection
=======
      - feature/ci-workflow-dockerhub
>>>>>>> 085ff44b38142fcaf07a0a2ee3037ab4dabfbf7d
jobs:
  # This section can't be done cause the problem to execute the api at the same time of the ui-web
  #sonnar-scanner-analysis:
    #runs-on: ubuntu-latest
    #steps:
    #  - name: Checkout Code
    #    uses: actions/checkout@v2
    #  - name: Setup Python
    #    uses: actions/setup-python@v2
    #    with:
    #      python-version: ${{ matrix.python }}
    #  - name: Install tox and any other packages
    #    run: pip install tox
    #  - name: Run tox
    #    run: tox -e py
    #  - name: SonarCloud Scan
    #    uses: sonarsource/sonarcloud-github-action@master
    #    env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #  - name: SonarQube Quality Gate check
    #    id: sonarqube-quality-gate-check
    #    uses: sonarsource/sonarqube-quality-gate-action@master
    #    timeout-minutes: 5
    #    env:
    #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #- name: "Example show SonarQube Quality Gate Status value"
      #  run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
  build-image:
    #if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aolguin89/bank-web-ui:${{ vars.MAJOR }}.${{ vars.MINOR }}-${{ github.run_number }}
